package agents

import (
	"context"
	"fmt"
	"time"

	"github.com/user/agentic-cicd/internal/models"
	"github.com/user/agentic-cicd/internal/services"
	"go.uber.org/zap"
)

type PRAgent struct {
	github *services.GitHubService
	logger *zap.Logger
}

func NewPRAgent(github *services.GitHubService, logger *zap.Logger) *PRAgent {
	return &PRAgent{
		github: github,
		logger: logger,
	}
}

func (a *PRAgent) CreateFixPR(ctx context.Context, event *models.PipelineEvent, analysis *models.AnalysisResult, fix *models.RepairResult) error {
	a.logger.Info("Creating automated Fix Pull Request", zap.String("repo", event.RepositoryName))

	branchName := fmt.Sprintf("agentic-fix-%s-%d", event.CommitSHA[:7], time.Now().Unix())

	title := fmt.Sprintf("Auto-Fix: %s", analysis.FailureType)
	body := fmt.Sprintf(`## Agentic DevOps Auto-Repair
	
**Root Cause:** 
%s

**Explanation of Fix:**
%s

**Confidence:** %s

*(This PR was automatically generated by the Agentic CI/CD System)*`, analysis.RootCause, fix.Explanation, analysis.Confidence)

	// In a real system, the patch string needs to be applied to create a new tree/commit before making the PR.
	// We abstract that inside CreatePullRequest for this example demo logic.
	_, err := a.github.CreatePullRequest(ctx, event.RepositoryOwner, event.RepositoryName, event.Branch, branchName, title, body, fix.Patch)

	if err != nil {
		return fmt.Errorf("failed to create PR: %v", err)
	}

	a.logger.Info("Successfully created Auto-Fix Pull Request", zap.String("branch", branchName))
	return nil
}
